apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: doom
  annotations:
    custom-hostname: doom.toska # staging.toska.dev
spec:
  template:
    spec:
      containers:
        - image: mattipaksula/ws-doom