name: Deploy

on:
  push:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        repository: toska/toska-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_sha: true

    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/knative-service.yaml
        images:  |
          toska/toska-dev:${{ github.sha }}