name: Release jami

on:
  push:
    branches: 
      - master
    paths:
      - 'jami/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v4
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: toska/toska-dev-jami
        image_tag: ${{ github.sha }}
        context: jami

    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          jami/manifests/deployment.yaml
          jami/manifests/service.yaml
        images:  |
          toska/toska-dev-jami:${{ github.sha }}