name: Release root

on:
  push:
    branches:
      - master
    paths:
      - 'root/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v4
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: toska/toska-dev-root
        image_tag: ${{ github.sha }}
        context: root

    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          root/manifests/deployment.yaml
          root/manifests/service.yaml
        images:  |
          toska/toska-dev-root:${{ github.sha }}