name: Release tuomo

on:
  push:
    branches: 
      - master
    paths:
      - 'tuomo/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v4
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        push_image_and_stages: false
        image_name: toska/toska-dev-tuomo
        image_tag: ${{ github.sha }}
        context: tuomo

    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          tuomo/manifests/deployment.yaml
          tuomo/manifests/service.yaml
        images:  |
          toska/toska-dev-tuomo:${{ github.sha }}