name: Release jami

on:
  push:
    branches: 
      - master
#    paths:
#      - 'jami/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: |
        cd jami
        docker build . -t toska/toska-dev-jami:${{ github.sha }}
        docker push toska/toska-dev-jami:${{ github.sha }}

    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          jami/manifests/deployment.yaml
          jami/manifests/service.yaml
        images:  |
          toska/toska-dev-jami:${{ github.sha }}