name: Release root

on:
  push:
    branches: [ master ]
    paths:
      - 'root/*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./root
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: toska/toska-dev-root:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
